exp_dir: '/nfs/masi/xuk9/SPORE/CAC_class/output/experiments22_pretrained'
input_img_dir: '/nfs/masi/xuk9/SPORE/CAC_class/data/s11_image_final_resample'
input_calcium_mask: '/nfs/masi/xuk9/SPORE/CAC_class/data/s12_mask_final_resample'
learning_rate: 0.00001   #default 0.0001
res:
  - 192
  - 128
  - 64
imsize:
  - 192
  - 128
  - 64
sample_size: 128
sample_duration: 64
batch_size: 2
fcnum: 1536
networkName: 'resnet101'
label_csv: '/nfs/masi/xuk9/SPORE/clustering/registration/20200512_corrField/male/clinical/label_full_combined.csv'
train_file_list_txt: '/nfs/masi/xuk9/SPORE/CAC_class/file_lists/train_list'
test_file_list_txt: '/nfs/masi/xuk9/SPORE/CAC_class/file_lists/test_list'
add_calcium_mask: True
data_augmentation: True
dual_network: False
use_siamese: False
ValidateAttention: False
siamese_coeiff: 0.0001
clss_num: 3
start_epoch: 100
epoch_num: 201